#!/usr/bin/perl -w
use strict;
use Imager;
use Cache::SharedMemoryCache;
use Time::Piece;
use List::Util qw(maxstr);
use Sysadm::Install qw(rmf mkd cd);
use File::Temp qw(tempdir);

my $dir = tempdir(CLEANUP => 1);

my $c = Cache::SharedMemoryCache->new({
    namespace => "tracker",
});

for my $date (sort $c->get_keys()) {

  next unless $date =~ /\d/;
  my $val = $c->get($date);
  my $img = Imager->new();
  $img->read(type => "jpeg", 
             data => $val);
  $date =~ s#/#-#g;
  $img->write(file => "$dir/$date.jpg") or 
      die "Can't write $!";
}

cd $dir;
my $str = "";
for (<*.jpg>) {
    (my $date = $_) =~ s/\.jpg//g;
    $str .= "-label $date $_ ";
}
`montage -tile 6x6 $str sequence.jpg`;
`xv $_` for <sequence*>;
