#!/usr/bin/perl
###########################################
use strict;
use warnings;
use Camcap;

my $cam = Camcap->new(width  => 640, 
                      height => 480);
$cam->cam_bright(42_000);
my $img = $cam->capture();
$img->write(file => 'buero.jpg') 
  or die "Can't write: $!";
